version: "3.8"

services:
  db:
    image: postgres:alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "carrinho"